## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestPhynot

# Rules for building the parser.

AbsPhynot.hs LexPhynot.x ParPhynot.y PrintPhynot.hs TestPhynot.hs : phynot.cf
	bnfc --haskell phynot.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestPhynot : AbsPhynot.hs LexPhynot.hs ParPhynot.hs PrintPhynot.hs TestPhynot.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsPhynot.hs AbsPhynot.hs.bak ComposOp.hs ComposOp.hs.bak DocPhynot.txt DocPhynot.txt.bak ErrM.hs ErrM.hs.bak LayoutPhynot.hs LayoutPhynot.hs.bak LexPhynot.x LexPhynot.x.bak ParPhynot.y ParPhynot.y.bak PrintPhynot.hs PrintPhynot.hs.bak SkelPhynot.hs SkelPhynot.hs.bak TestPhynot.hs TestPhynot.hs.bak XMLPhynot.hs XMLPhynot.hs.bak ASTPhynot.agda ASTPhynot.agda.bak ParserPhynot.agda ParserPhynot.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak phynot.dtd phynot.dtd.bak TestPhynot LexPhynot.hs ParPhynot.hs ParPhynot.info ParDataPhynot.hs Makefile


# EOF
