-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelPhynot where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsPhynot

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsPhynot.Ident -> Result
transIdent x = case x of
  AbsPhynot.Ident string -> failure x

transBasicType :: AbsPhynot.BasicType -> Result
transBasicType x = case x of
  AbsPhynot.BasicType_int -> failure x
  AbsPhynot.BasicType_float -> failure x
  AbsPhynot.BasicType_char -> failure x
  AbsPhynot.BasicType_String -> failure x
  AbsPhynot.BasicType_bool -> failure x

transBoolean :: AbsPhynot.Boolean -> Result
transBoolean x = case x of
  AbsPhynot.Boolean_True -> failure x
  AbsPhynot.Boolean_False -> failure x

transProgram :: AbsPhynot.Program -> Result
transProgram x = case x of
  AbsPhynot.ProgramStart stms -> failure x

transStm :: AbsPhynot.Stm -> Result
transStm x = case x of
  AbsPhynot.VarDeclaration basictype ident -> failure x
  AbsPhynot.VarDeclarationInit basictype ident rexp -> failure x
  AbsPhynot.ArrayDeclaration basictype ident dims -> failure x
  AbsPhynot.ArrayDeclarationInit basictype ident dims rexp -> failure x
  AbsPhynot.PointerDeclaration basictype ident -> failure x
  AbsPhynot.PointerDeclarationInit basictype ident rexp -> failure x
  AbsPhynot.FunctionDeclaration basictype ident params stms -> failure x
  AbsPhynot.FunctionNoParamDeclaration basictype ident stms -> failure x
  AbsPhynot.ProcedureDeclaration ident params stms -> failure x
  AbsPhynot.ProcedureNoParamDeclaration ident stms -> failure x
  AbsPhynot.ProcedureCall ident rexps -> failure x
  AbsPhynot.ProcedureCallNoParam ident -> failure x
  AbsPhynot.Return rexp -> failure x
  AbsPhynot.ReturnNone -> failure x
  AbsPhynot.Assignment lexp rexp -> failure x
  AbsPhynot.WriteInt rexp -> failure x
  AbsPhynot.WriteFloat rexp -> failure x
  AbsPhynot.WriteChar rexp -> failure x
  AbsPhynot.WriteString rexp -> failure x
  AbsPhynot.ReadInt -> failure x
  AbsPhynot.ReadFloat -> failure x
  AbsPhynot.ReadChar -> failure x
  AbsPhynot.ReadString -> failure x
  AbsPhynot.IfThen rexp stms -> failure x
  AbsPhynot.IfThenElse rexp stms1 stms2 -> failure x
  AbsPhynot.WhileDo rexp stms -> failure x
  AbsPhynot.Break -> failure x
  AbsPhynot.Continue -> failure x
  AbsPhynot.Pass -> failure x

transParam :: AbsPhynot.Param -> Result
transParam x = case x of
  AbsPhynot.Parameter basictype ident -> failure x

transDim :: AbsPhynot.Dim -> Result
transDim x = case x of
  AbsPhynot.ArrayDimension rexp -> failure x

transLExp :: AbsPhynot.LExp -> Result
transLExp x = case x of
  AbsPhynot.LIdent ident -> failure x
  AbsPhynot.LArray ident dims -> failure x

transRExp :: AbsPhynot.RExp -> Result
transRExp x = case x of
  AbsPhynot.Or rexp1 rexp2 -> failure x
  AbsPhynot.And rexp1 rexp2 -> failure x
  AbsPhynot.Not rexp -> failure x
  AbsPhynot.Eq rexp1 rexp2 -> failure x
  AbsPhynot.Neq rexp1 rexp2 -> failure x
  AbsPhynot.Lt rexp1 rexp2 -> failure x
  AbsPhynot.Gt rexp1 rexp2 -> failure x
  AbsPhynot.Le rexp1 rexp2 -> failure x
  AbsPhynot.Ge rexp1 rexp2 -> failure x
  AbsPhynot.Add rexp1 rexp2 -> failure x
  AbsPhynot.Sub rexp1 rexp2 -> failure x
  AbsPhynot.Mul rexp1 rexp2 -> failure x
  AbsPhynot.Div rexp1 rexp2 -> failure x
  AbsPhynot.Mod rexp1 rexp2 -> failure x
  AbsPhynot.PointerRef rexp -> failure x
  AbsPhynot.DereferenceVal rexp -> failure x
  AbsPhynot.IntValue integer -> failure x
  AbsPhynot.FloatValue double -> failure x
  AbsPhynot.StringValue string -> failure x
  AbsPhynot.CharValue char -> failure x
  AbsPhynot.BooleanValue boolean -> failure x
  AbsPhynot.VarValue ident -> failure x
  AbsPhynot.ArrayEntry ident dims -> failure x
  AbsPhynot.FuncCall ident rexps -> failure x
  AbsPhynot.FuncCallNoParam ident -> failure x
